### PR TITLE
Support c++03

### PR DESCRIPTION
**Pull request by 414owen**
I'm making this a separate PR, as I'm not 100% sure I haven't messed up unicode support.

@tek are there tests that include unicode? Specifically on the `symop` codepath?

@wenkokke do you want to try compiling this branch to wasm?

### CODE REVIEW

**Comment by wenkokke** [comment]
This version leaves me with the following error message:
```
Error: bad export type for `_ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE`: undefined
```

**Comment by 414owen** [comment]
Huh, weird. Guess it doesn't like `ostringstream`...

Do you have a branch, and a command I can run to compile this for wasm?

**Comment by wenkokke** [comment]
Yep, it's right here: https://github.com/wenkokke/tree-sitter-haskell/tree/tree-sitter-haskell-wasm-support-c%2B%2B03

I'm running...
```bash
make -B node_modules/web-tree-sitter && CXX=g++-11 ./script/parse-examples wasm
```
...to rebuild a patched version of tree-sitter and run the wasm tests.

**Comment by wenkokke** [comment]
I am making progress however by using `ostringstream` we're definitely incurring a tree-sitter patch, and I'm afraid a rather large one.

**Comment by wenkokke** [comment]
I was wrong, the following patch is enough:
```diff
--- a/lib/binding_web/exports.json
+++ b/lib/binding_web/exports.json
@@ -3,6 +3,11 @@
   "_free",
   "_malloc",

+  "__ZTTNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE",
+  "__ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE",
+  "__ZTVNSt3__29basic_iosIcNS_11char_traitsIcEEEE",
+  "__ZNSt3__25ctypeIcE2idE",
+
   "__ZNKSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE4copyEPcmm",
   "__ZNKSt3__220__vector_base_commonILb1EE20__throw_length_errorEv",
   "__ZNSt3__212basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEE6__initEPKcm",
```
Unfortunately, that still means a patch is needed.

**Comment by wenkokke** [comment]
> This version leaves me with the following error message:
> 
> ```
> Error: bad export type for `_ZTVNSt3__219basic_ostringstreamIcNS_11char_traitsIcEENS_9allocatorIcEEEE`: undefined
> ```

This error was because I was accidentally running a version of web-tree-sitter compiled without `--debug`, which I didn't notice because usually the errors that you get without `--debug` are just "failed: undefined".

**Comment by wenkokke** [comment]
However, I can report that this runs without any problems on macOS:
```sh
npx tree-sitter parse [file] # works!
npx tree-sitter test         # works!
npx tree-sitter build-wasm   # works, but requires patched web-tree-sitter
```
So patch or no patch, it's probably still worth merging to get proper macOS support.

**Comment by 414owen** [comment]
@wenkokke I've removed ostringstream. Maybe `__ZNSt3__25ctypeIcE2idE` is still needed?

**Comment by 414owen** [comment]
I'm going to create a PR upstream, because it's quite helpful in terms of portability [eg.](https://github.com/helix-editor/helix/pull/1417)

We can deal with the remaining wasm patch, if there is one, separately.

**Comment by 414owen** [comment]
see https://github.com/tree-sitter/tree-sitter-haskell/pull/58

**Pull request closed without merging**
